language: scala

scala:
- 2.12.8

jdk:
- oraclejdk8

install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install

env:
  global:
    JSENV=node

script:
  - sbt ++$TRAVIS_SCALA_VERSION testDev testProd

deploy:
  provider: script
  script:
  - /bin/bash "$TRAVIS_BUILD_DIR/.travis.credentials.sh" && sbt ++$TRAVIS_SCALA_VERSION publish
  on:
    tags: true

env:
  global:
  # travis encrypt BINTRAY_USER=xxx
  - secure: "Tunbcs7UhcZXFzsb/qNxf+HXjVZdRwQcThJzfEKBYP/FwpvtY3F0IJ3Ukq/FPLsUHQHTbXKJ5I9l9wbZ9skD0ZJ4lnv7dm7a8Td0AJ0wezDj67EhSFwR8IF+2bTkCfOPdvT4fiBWJHSDiQ0zeN599IFbieMFmtXJeceWtzRAphfLvd9qtv7kEba5reTB4/ETAgtClTQFPlCAtl9l+D63yB5+8pn3HNHYmhGEZc92osHfxlENmZsrHBcjtZywF1fTXdNM/j/s6hICmnZREabFX0lFvj2x/9moelg2hzb/d9xVkH2/IlzrsQbA7Men1qWWfGjWdBzABHNUcooxmfxdYtHEnuJ5NpIaDux3c2eOylHxw8tfGQDtRKI7/4y8kX0+g2K4iFB6tJYxqWJcFB8WVIL3Gfo0cCmFYK36O7Cqe4yncbPZgjoWfL+RwlyJ8ZxTXDI9FfkxW8NuOWcbNDYlwNYzlSeL2FVYR+5XZYyxY/NKJvlbCHQltKM81s8lnNovbgaT4ex0CAalKu73pwjuh+KBlUhdrdtmSoQgxGNeihnjiHDniJ1zZUw3birNbV05ACq44v4TGlUEdhsnUcd0ovahTStHcnJVEI4RH4X6eQIw+x0Qqmb1lJ5Pa6/pj0DB8CcabP5tKqM79zb6pILjExqo7O0FxLgNjmLACT+0hTw="
  # travis encrypt BINTRAY_PASSWORD=xxx
  - secure: "k3QNTKw7Ix7kn46UMU9BO2fi3bcric1sFT52frfJUn0Tqw+Nb+wpAAMy+rC9HnWUSGfOVtb28yvUN8im2Cyx8sZh3swvDyCzEN/Bvtu09UKzbKfOpXJHmsmqNxSWlPU6hst93UsK1avf5jnGn2wv3nWENMkVElX3avKLjaeRfWslDV846A8qEPZXsDNHA1jjkPvaTgBNQXOI/86GqCvuMcrIR8SMTZwOoGtc5smmvw7iqtLLrbwp0w3TFHvzzaFHDLZFg3uTbdOjENiv2tbSguv2EdI0uYJYVgdZ68eCsdGM4Y1uuSYfo6AY8atZEJ+cqMDcI2QsqdoQEvtIRlvuYEgKvZDlU87D4SjbCDgG01INYJfmrU1/dURzNryYd/yhCw+gvklpjeTFBqd7kaJbD8NhZrBKEdnVyhx7S6M+oTeWegzdkqvSv+h5tuIqDHyRUWwwPrJz9a124bUHLzhpy8zDFxfAQTlcWh76qoPiNapU39Gq2VFQavmK+h0FmvtUhhQBrmkdN9Z7nEpSyKSvc6Q9QUn3oi48HfMiCmY03Fe7S5p7Afb0zwgHszVIE+KsCTAjjnlOH48BPookeTosBB1eAv0eJL87wJ/TVQkLJYuvdCwIg3MV4DTe83YezITAQc0ppKfvd1OVD8IPlf3xWbMCS9ve3muLh0CDsxwFOG0="

